# 1. Guessing the the random number between 23 to 78 that is generated by system
# Here we are going to use the While loop with if and elseif conditions
from xml.dom.minidom import ProcessingInstruction

# Firstly importing the random numbers

import random

number = random.randint(23,78)

# I am starting from 0 attempts to multiple attemps until going to identify the system generatenumber

attempts = 0

print("Guess the number generated between 23 to 78")

#Using while loop to generate the output to identify the system generated random number

while True:
    guess = int(input("Guess the Number:"))
    attempts += 1

    if guess > number:
        print("Provided value is too high, please try again")

    elif guess < number:
        print("Provided value is too low, please try again")

    else:
        print("Congratulations you have got the number")

        break




import random

# Word Scrambler for the given words

Word = ['python', 'javascript', 'java', 'automation', 'pytest', 'guvi', 'selenium']

# function for scrambiling of each word
def scramble_word(word):
    word_list = list(word)
    random.shuffle(word_list)
    return ''.join(word_list)

scramble_word = [scramble_word(Word) for Word in Word]

print("Welcome to the Unscramble Game!")
print("Try to unscramble the following words:")

for i, scrambled in enumerate(scramble_word, 1):
    print(f"{i}. {scrambled}")
    correct_answers = 0

    for i, scrambled in enumerate(scramble_word):
        guess = input(f"Unscramble the word #{i}: {scrambled} = ").strip().lower()

        # Check if the player's guess is correct
        original_word = Word[i - 1]
        if guess == original_word:
            print("Correct!")
            correct_answers += 1
        else:
            print(f"Oops! The correct word was {original_word}.")

    # Display final score
    print(f"\nYou got {correct_answers} out of {len(word)} correct!")















